############################################################
# Ping Identity
#
############################################################


global:
  image:
    tag: "edge"  # Uses images with the "edge" tag
    pullPolicy: Always

pingaccess:
  enabled: true
  # There are known issues with certificates when release names affect the hostname.
  # We hope to resolve those soon.  For now, the default getting-started server profile
  # is used.
  #
  envs:
    SERVER_PROFILE_URL: https://github.com/chrisleggett/pa-cert-server-profile.git
    SERVER_PROFILE_PATH: pingaccess